apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "hml-ec2-test"
  environment:
    cluster_type: ec2
    domain: vee.codes
    ingress_type: kong  
  annotations:
    github.com/project-slug: veecode-homolog/hml-ec2-test
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,deploy-dashboard,infracost.yml
    grafana/dashboard-selector: hml-ec2-test
    grafana/alert-label-selector: "alertname=hml-ec2-test"
    infracost/project: hml-ec2-test
    cluster/instructions: |
      ssh -i ./key-pair.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 
      "mkdir -p .kube && k3d kubeconfig get ${CLUSTER_NAME} > ~/.kube/config"
      scp -i ./key-pair.pem ${EC2_USER}@${EC2_HOST}:~/.kube/config ./config
      yq e 'del(.clusters[0].cluster.certificate-authority-data)' -i ~/.kube/config
      yq e '.clusters[0].cluster.insecure-skip-tls-verify=true' config -i
      yq e '.clusters[0].cluster.server = "https://${EC2_HOST}:38517"' config -i
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_environment'
  
